keys:
  - &framework age176e8uyk9wdhszj8qghksmz73vfu0pwdcw9p4pg65l4e05v56s4lqr7eukm
  - &beelink age1cz3hmpxd9af4tms7g5zak0zmrj7xv7g3dwnjvcewevhnggcnkugqa63pqx

creation_rules:
  # Shared secrets (accessible by all systems)
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *framework
          - *beelink

  # Framework-specific secrets
  - path_regex: secrets/framework\.yaml$
    key_groups:
      - age:
          - *framework

  # Beelink-specific secrets
  - path_regex: secrets/beelink\.yaml$
    key_groups:
      - age:
          - *beelink
