keys:
  - &framework age176e8uyk9wdhszj8qghksmz73vfu0pwdcw9p4pg65l4e05v56s4lqr7eukm
  - &beelink age1c9h04fjl3fk9yggdeyu9hakhm97wtyl7wdektdj5mv9t5u8vxd0skc6sh8

creation_rules:
  # Shared secrets (accessible by all systems)
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *framework
          - *beelink

  # Framework-specific secrets
  - path_regex: secrets/framework\.yaml$
    key_groups:
      - age:
          - *framework

  # Beelink-specific secrets
  - path_regex: secrets/beelink\.yaml$
    key_groups:
      - age:
          - *beelink
