keys:
  # Framework laptop key
  - &framework age176e8uyk9wdhszj8qghksmz73vfu0pwdcw9p4pg65l4e05v56s4lqr7eukm
  # Beelink mini PC key (generate with: ./scripts/bootstrap-secrets.sh beelink)
  # - &beelink age1REPLACE_WITH_ACTUAL_BEELINK_KEY

creation_rules:
  # Shared secrets (accessible by all systems)
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *framework
          # - *beelink

  # Framework-specific secrets
  - path_regex: secrets/framework\.yaml$
    key_groups:
      - age:
          - *framework

  # Beelink-specific secrets
  # - path_regex: secrets/beelink\.yaml$
  #   key_groups:
  #     - age:
  #         - *beelink
