{
  config,
  pkgs,
  inputs,
  ...
}: let
  astal = inputs.astal.packages.${pkgs.stdenv.hostPlatform.system};

  # Generate a _colors.scss from Stylix so style.scss can @import "colors"
  colorsScss = ''
    // Auto-generated by ags.nix — do not edit
    $base00: #${config.lib.stylix.colors.base00};
    $base01: #${config.lib.stylix.colors.base01};
    $base02: #${config.lib.stylix.colors.base02};
    $base03: #${config.lib.stylix.colors.base03};
    $base04: #${config.lib.stylix.colors.base04};
    $base05: #${config.lib.stylix.colors.base05};
    $base06: #${config.lib.stylix.colors.base06};
    $base07: #${config.lib.stylix.colors.base07};
    $base08: #${config.lib.stylix.colors.base08};
    $base09: #${config.lib.stylix.colors.base09};
    $base0A: #${config.lib.stylix.colors.base0A};
    $base0B: #${config.lib.stylix.colors.base0B};
    $base0C: #${config.lib.stylix.colors.base0C};
    $base0D: #${config.lib.stylix.colors.base0D};
    $base0E: #${config.lib.stylix.colors.base0E};
    $base0F: #${config.lib.stylix.colors.base0F};

    // RGB channel variables for rgba() usage
    $base00-r: ${config.lib.stylix.colors.base00-rgb-r};
    $base00-g: ${config.lib.stylix.colors.base00-rgb-g};
    $base00-b: ${config.lib.stylix.colors.base00-rgb-b};
    $base0D-r: ${config.lib.stylix.colors.base0D-rgb-r};
    $base0D-g: ${config.lib.stylix.colors.base0D-rgb-g};
    $base0D-b: ${config.lib.stylix.colors.base0D-rgb-b};
  '';
in {
  imports = [inputs.ags.homeManagerModules.default];

  programs.ags = {
    enable = true;
    systemd.enable = true;
    # Build a single store path with source files + generated colors merged in,
    # so configDir gets one clean directory and relative imports work.
    configDir = let
      colorsFile = pkgs.writeText "_colors.scss" colorsScss;
    in
      pkgs.runCommand "ags-config" {} ''
        mkdir -p $out/bar
        cp ${./ags/app.ts}          $out/app.ts
        cp ${./ags/style.scss}      $out/style.scss
        cp ${./ags/tsconfig.json}   $out/tsconfig.json
        cp ${colorsFile}            $out/_colors.scss
        cp ${./ags/bar/Bar.tsx}     $out/bar/Bar.tsx
      '';
    extraPackages = [
      astal.astal3
      astal.io
      astal.hyprland
      astal.wireplumber
      astal.network
      astal.bluetooth
      astal.mpris
      astal.notifd
    ];
  };

  # Packages needed at runtime by the bar
  home.packages = with pkgs; [
    blueman
    networkmanagerapplet
    pavucontrol
    wireplumber
    playerctl
    dart-sass
  ];
}
